FROM centos
MAINTAINER Charitra Maharjan charitra.maharjan1@gmail.com
RUN yum update -y \
    && yum install -y epel-release \
    && yum install -y nginx \
    && yum -y clean all

ENV container docker
RUN yum -y install systemd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ “/sys/fs/cgroup” ]
EXPOSE 80
CMD [“/usr/sbin/init”]

RUN systemctl enable nginx


